### PR TITLE
chore: add new orange and green base colors

### PR DESCRIPTION
**Pull request by Thunear**
Adding new base colors for orange and green so the contrast color becomes white.

image

### CODE REVIEW

**Comment by Barsnes** [comment]
This does not update any tokens, should it?
image

**Comment by Thunear** [comment]
> This does not update any tokens, should it? image

No. This is just so that Lasse kan copy in the new tokens into Figma. He will then generate new tokens that will be pushed to code in a PR later.

**Review by Barsnes — APPROVED** [review]

**Comment by mimarz** [comment]
This will be a merge conflict with #2290

**Comment by mimarz** [comment]
Fixed the conflict, is it ok @Thunear ?

**Comment by Thunear** [comment]
Yes this is great!

**Pull request merged**
