### PR TITLE
feat(DropdownMenu, Popover, Modal): Using `asChild` on `Trigger` components no longer clones style to child

### LINKED ISSUE #1794: Using `asChild` on `*.Trigger` components should not clone parent styling
When using `asChild` on utility/helper components such as `Trigger`, the styling from "default" component should not bleed over to the child component. 

Example of bug: https://codesandbox.io/p/sandbox/frosty-architecture-39tkw4?file=%2Fsrc%2FApp.tsx%3A16%2C30

### PR DESCRIPTION
**Pull request by mimarz**
resolves #1794 

BREAKING CHANGE: `DropdownMenu.Trigger`, `Modal.Trigger` & `Popover.Trigger` no longer clone style to child on `asChild`

- Reverted changes on hos Slot vs default component is used in `Trigger` components
- Updated `DropdownMenu` stories to use `asChild`
- Updated `Box` stories to use `asChild`

### CODE REVIEW

**Review by Barsnes — APPROVED** [review]
Everything looks to be in order here 💯

**Comment by Barsnes** [comment]
We should probably do this for `ModalTrigger` as well

**Comment by mimarz** [comment]
> We should probably do this for `ModalTrigger` as well

Done ✅

**Comment by Barsnes** [comment]
> > We should probably do this for `ModalTrigger` as well
> 
> Done ✅

Looks good, approve still stands 😄

**Pull request merged**
