### PR TITLE
style(TableCell): Add background color

### LINKED ISSUE #1692: `Table.Cell` has transparent background color
### Description of the bug

Use a table, see that it's background is transparent.

In this image I have zebra set to true - and since the background of he page is the same color as the stripes, they are not visible
image
image

The background color should be white

### Steps To Reproduce

Use the table

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by Barsnes**
Resolves #1692

### CODE REVIEW

**Comment by mimarz** [comment]
Is it not better to have background color on the row instead of each individual cell?

**Comment by Barsnes** [comment]
> Is it not better to have background color on the row instead of each individual cell?

hmm, I don't think it really matters 🤔 
Can change it if you think it is cleaner

**Comment by mimarz** [comment]
> > Is it not better to have background color on the row instead of each individual cell?
> 
> hmm, I don't think it really matters 🤔 Can change it if you think it is cleaner

Suggest adding to row as we never know how people might use this and its semantically correct. It will also add the background to header if you put it on the row, which is missing now?

**Review by mimarz — APPROVED** [review]
Not to fussed if its cell or row, either work and we can just change it if it doesn't :)

**Pull request merged**
