### PR TITLE
feat(theme): 🎨 apps/theme enabled in all linters

### PR DESCRIPTION
**Pull request by poi33**
Fix for #2005

Included apps/theme in tsconfig root
Extended apps/theme tsconfig to include the root tsconfig
Fixed eslint errors/warnings
No longer ignore apps/theme in stylelintignore
Fixed stylelint errors

### CODE REVIEW

**Comment by mimarz** [comment]
Sorry, we didn't flag the issue correctly but we have done a lot of these changes and other for the upcoming release of V1. All the changes that have been done that regards is in the `next` branch. I changed the target for you on this PR to check how many conflict would occur 🙈

**Comment by poi33** [comment]
@mimarz thats okay. I will like to see what i did is even close to the next branch.

**Comment by mimarz** [comment]
> @mimarz thats okay. I will like to see what i did is even close to the next branch.

Alrighty. We haven't sorted out all our environments yet. Going forward `next` will be the development branch and `main` be whats currently published to production/(`@latest`).

**Comment by mimarz** [comment]
Can we close this or did you want to look at it more? @poi33 ?

**Comment by poi33** [comment]
Yeah, I'll close it. Its not going to contribute much

**Pull request closed without merging**
