### PR TITLE
chore(ToggleGroup): pass `data-color` down to button

### LINKED ISSUE #2834: `ToggleGroup` does not adher to `data-color`
When using `data-color` on `ToggleGroup` I expect the buttons to change according to defined color scope, this does not happen now.

### PR DESCRIPTION
**Pull request by Barsnes**
resolves #2834

Consulted with @Thunear, we will leave the border color neutral for now.

### CODE REVIEW

**Comment by mimarz** [comment]
Would this not work better if we just fixed this in `button.css`?


```css
.ds-button {
  /* default color: accent */
  --dsc-button-background--active: var(--ds-color-base-active);
  --dsc-button-background--hover: var(--ds-color-base-hover);
  --dsc-button-background: var(--ds-color-base-default);
  --dsc-button-color: var(--ds-color-contrast-default);
  --dsc-button-color--hover: var(--ds-color-contrast-default);
  
  …
}
```

The nameless color props are defined in `:root` with the first color added in theme builder. 
```css
:root, [data-color-scheme], [data-color="accent"] {
  --ds-color-background-default: var(--ds-color-accent-background-default);
  --ds-color-background-subtle: var(--ds-color-accent-background-subtle);
  --ds-color-surface-default: var(--ds-color-accent-surface-default);
  --ds-color-surface-hover: var(--ds-color-accent-surface-hover);
  --ds-color-surface-active: var(--ds-color-accent-surface-active);
  --ds-color-border-subtle: var(--ds-color-accent-border-subtle);
  --ds-color-border-default: var(--ds-color-accent-border-default);
  --ds-color-border-strong: var(--ds-color-accent-border-strong);
  --ds-color-base-default: var(--ds-color-accent-base-default);
  --ds-color-base-hover: var(--ds-color-accent-base-hover);
  --ds-color-base-active: var(--ds-color-accent-base-active);
  --ds-color-text-subtle: var(--ds-color-accent-text-subtle);
  --ds-color-text-default: var(--ds-color-accent-text-default);
  --ds-color-contrast-default: var(--ds-color-accent-contrast-default);
  --ds-color-contrast-subtle: var(--ds-color-accent-contrast-subtle);
}
```

**Comment by Barsnes** [comment]
> Would this not work better if we just fixed this in `button.css`?
> 
> ```css
> .ds-button {
>   --dsc-button-background--active: var(--ds-color-base-active);
>   --dsc-button-background--hover: var(--ds-color-base-hover);
>   --dsc-button-background: var(--ds-color-base-default);
>   --dsc-button-color: var(--ds-color-contrast-default);
>   --dsc-button-color--hover: var(--ds-color-contrast-default);
>   
>   …
> }
> ```
> 
> The nameless color props are defined in `:root` with the first color added in theme builder.
> 
> ```css
> :root, [data-color-scheme], [data-color="accent"] {
>   --ds-color-background-default: var(--ds-color-accent-background-default);
>   --ds-color-background-subtle: var(--ds-color-accent-background-subtle);
>   --ds-color-surface-default: var(--ds-color-accent-surface-default);
>   --ds-color-surface-hover: var(--ds-color-accent-surface-hover);
>   --ds-color-surface-active: var(--ds-color-accent-surface-active);
>   --ds-color-border-subtle: var(--ds-color-accent-border-subtle);
>   --ds-color-border-default: var(--ds-color-accent-border-default);
>   --ds-color-border-strong: var(--ds-color-accent-border-strong);
>   --ds-color-base-default: var(--ds-color-accent-base-default);
>   --ds-color-base-hover: var(--ds-color-accent-base-hover);
>   --ds-color-base-active: var(--ds-color-accent-base-active);
>   --ds-color-text-subtle: var(--ds-color-accent-text-subtle);
>   --ds-color-text-default: var(--ds-color-accent-text-default);
>   --ds-color-contrast-default: var(--ds-color-accent-contrast-default);
>   --ds-color-contrast-subtle: var(--ds-color-accent-contrast-subtle);
> }
> ```

Button should not follow the closes data-color set, it neeeds to be explicitly set, with accent being default.
This was decided on when we implemented `data-color`

**Comment by mimarz** [comment]
> Button should not follow the closes data-color set, it neeeds to be explicitly set, with accent being default. This was decided on when we implemented `data-color`

Ah, true, but maybe we need to revisit this decision? When testing it now, and making a normal form, having `Checkbox` and `Radio` following closest `data-color` and `Button` _not_ doing so felt weird to use.

**Comment by mimarz** [comment]
This will be solved by #2836

**Pull request closed without merging**
