### PR TITLE
feat(storefront): Make Bloggen

### LINKED ISSUE #1539: Develop blog post and blog archive layout

### PR DESCRIPTION
**Pull request by Barsnes**
Resolves #1539

### CODE REVIEW

**Review by mimarz — APPROVED** [review]
Suggest using "bloggen" as url name also :D

**Comment by Barsnes** [comment]
> Suggest using "bloggen" as url name also :D

@Thuneer

**Comment by Thuneer** [comment]
> > Suggest using "bloggen" as url name also :D
> 
> @Thuneer
Agreed! More consistant.

**Comment by Barsnes** [comment]
> > > Suggest using "bloggen" as url name also :D
> > 
> > 
> > @Thuneer
> > Agreed! More consistant.

Updated 👍🏻

**Pull request merged**
