### PR TITLE
feat(Skeleton): text wrapping

### PR DESCRIPTION
**Pull request by eirikbacker**
- Fixes [#2518](https://github.com/digdir/designsystemet/issues/2518)
- Discussed with design ✅

### CODE REVIEW

**Review by Barsnes — CHANGES_REQUESTED** [review]
You need to update some stories so they work with the new text variant:
image
image

It also seems like the height of text is now broken again,
old left, this pr right
image

**Comment by eirikbacker** [comment]
> It also seems like the height of text is now broken again, old left, this pr right image

Stories updated, but the height is not broken - it is how tall the font is when including the height of ascender and descender of the characters. Our previous implementation relied on a `::before` element, shrinking the skeleton area to `60%` of the font height. When using `box-decoration-break`, we need to also use `display: inline` - this is verified with Lasse but I can do another round on it ☺️ 

image

**Comment by Barsnes** [comment]
> > It also seems like the height of text is now broken again, old left, this pr right image
> 
> Stories updated, but the height is not broken - it is how tall the font is when including the height of ascender and descender of the characters. Our previous implementation relied on a `::before` element, shrinking the skeleton area to `60%` of the font height. When using `box-decoration-break`, we need to also use `display: inline` - this is verified with Lasse but I can do another round on it ☺️
> 
> image

As long as this is cleared with design, and it will be updated in figma to match this, it's fine

**Review by Barsnes — APPROVED** [review]
💀

**Pull request merged**
