### PR TITLE
fix(combobox): only set `aria-controls` when open, fix reference id to list

### LINKED ISSUE #2552: Combobox: WCAG issue 4.1.2 found with ARC toolkit
### Version number

0.63.0 (and the version used in https://theme.designsystemet.no/)

### Description of the bug

When running ARC toolkit accessibility test on the Combobox component a violation is found.
image
image
image

### Steps To Reproduce

1. Go to https://theme.designsystemet.no/
2. Open devtools and run ARC toolkit: https://chromewebstore.google.com/detail/arc-toolkit/chdkkkccnlfncngelccgbgfmjebmkmce
3. find the violation "Aria attribute value is incorrect" on the combobox that chooses a destination under the heading "Hvor skal du reise?"

### Additional Information

This issue was reported to Team Apps from UDIR as part of the WCAG tests they performed in preparation of the "Lærlingundersøkelsen" og senere "Elevundersøkelsen". They are going live next week and it would be ideal if we could get a fix for this as soon as possible in order to go live with as few WCAG violations as possible. @RonnyB71 @mimarz 

Related issues:
- https://github.com/Altinn/app-frontend-react/issues/2517#event-14477079311

### PR DESCRIPTION
**Pull request by Barsnes**
**DO NOT MERGE THIS TO MAIN**

This has been synced in our next branch with PR ##2576

resolves #2552

This solves the issue by not adding `aria-controls` until the popup is visible (and in the DOM).
This also makes use of floating uis internal id, so the id is also correct.

### CODE REVIEW

**Comment by Barsnes** [comment]
Setting this as ready for review, but will not be merging when approved.
After approval a release for version 0.63.1 will be done

**Review by eirikbacker — APPROVED** [review]
👌

**Comment by Magnusrm** [comment]
Tested with ARC toolkit and the error is no longer reported. I have not tested using a JAWS screen-reader though, as i dont have a license. 😅

**Comment by Barsnes** [comment]
Great! I'll fix the storybook deployment and get a release going

**Comment by mimarz** [comment]
Closing PR but not deleting branch

**Pull request closed without merging**
