### PR TITLE
build: Relative hash for css-modules

### PR DESCRIPTION
**Pull request by mimarz**
Now that we have checked in css thats generated from css-modules we need to change the hash for css-module classNames to be relative. 

It was using the absolute path for files before, which resulted in new classNames being generated for every unique location and build of source code.

### CODE REVIEW

**Comment by mimarz** [comment]
Can you checkout and test this running build? If it works as intended, there should be no changes to `css/react-css-modules.css`

**Comment by Thuneer** [comment]
Ran `yarn build` in that branch and it created a new hash string at the end of the classnames.
image

**Comment by Barsnes** [comment]
I experience the same as @Thuneer, but it does look like we got the same hashes.
Could this be a difference between mac and windows?
image

**Comment by mimarz** [comment]
@Barsnes @Thuneer I have updated the gitattributes files. Pull latest run the following commands:
```sh
git rm --cached -r .  # Remove every file from git's index.
git reset --hard      # Rewrite git's index to pick up all the new line endings
```

**Comment by Barsnes** [comment]
> @Barsnes @Thuneer I have updated the gitattributes files. Pull latest run the following commands:
> 
> ```shell
> git rm --cached -r .  # Remove every file from git's index.
> git reset --hard      # Rewrite git's index to pick up all the new line endings
> ```

No files changed after doing that 😄

**Review by Barsnes — APPROVED** [review]
🚀

**Comment by mimarz** [comment]
Waiting for @Thuneer to test before merging

**Comment by Thuneer** [comment]
No files changed here either after running those commands! Let's goooo! 🎉

**Pull request merged**
